server:
    port: 8080

logging:
    level:
        com:
            tonyzampogna: DEBUG

spring:
    kafka:
        bootstrap-servers: localhost:9092
        properties:
            state-store-directory: /var/stream-data/
        consumer:
            group-id: streams-example
            auto-offset-reset: latest
